# Generated by Django 4.1 on 2022-08-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=225)),
                ('userDeliveryDate', models.DateField()),
                ('userPhone', models.BigIntegerField()),
                ('userAdvance', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
