# Generated by Django 4.1 on 2022-08-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0002_customer_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest1', models.IntegerField()),
                ('chest2', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('topheapRound', models.IntegerField()),
                ('topKurtiArmHole', models.IntegerField()),
                ('topKurtiWaist', models.IntegerField()),
                ('topKurtiLength', models.IntegerField()),
                ('topKurtiSleeveL', models.IntegerField()),
                ('topKurtiSleeveR', models.IntegerField()),
                ('topKurtiNeckF', models.IntegerField()),
                ('topKurtiNeckB', models.IntegerField()),
                ('topGownArmHole', models.IntegerField()),
                ('topGownWaist', models.IntegerField()),
                ('topGownLength', models.IntegerField()),
                ('topGownSleeveL', models.IntegerField()),
                ('topGownSleeveR', models.IntegerField()),
                ('topGownNeckF', models.IntegerField()),
                ('topGownNeckB', models.IntegerField()),
                ('topBlouseArmHole', models.IntegerField()),
                ('topBlouseWaist', models.IntegerField()),
                ('topBlouseLength', models.IntegerField()),
                ('topBlouseSleeveL', models.IntegerField()),
                ('topBlouseSleeveR', models.IntegerField()),
                ('topBlouseNeckF', models.IntegerField()),
                ('topBlouseNeckB', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BottomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottomWaist', models.IntegerField()),
                ('bottomHeapRound', models.IntegerField()),
                ('bottomSalwarMori', models.IntegerField()),
                ('bottomSalwarLength', models.IntegerField()),
                ('bottomPantMori', models.IntegerField()),
                ('bottomPantLength', models.IntegerField()),
                ('bottomPlazoMori', models.IntegerField()),
                ('bottomPlazoLength', models.IntegerField()),
                ('bottomChaniyaMori', models.IntegerField()),
                ('bottomChaniyaLength', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer')),
            ],
        ),
    ]
