# Generated by Django 4.1 on 2022-08-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0003_topdetails_bottomdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BottomDetails',
            new_name='BottomDetail',
        ),
        migrations.RenameModel(
            old_name='TopDetails',
            new_name='TopDetail',
        ),
    ]
