# Generated by Django 4.1 on 2022-08-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0004_rename_bottomdetails_bottomdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer'),
        ),
        migrations.AlterField(
            model_name='topdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer'),
        ),
    ]
