# Generated by Django 4.1 on 2022-09-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0005_alter_bottomdetail_user_alter_topdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], default='high', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer')),
            ],
        ),
    ]
