# Generated by Django 4.1 on 2022-09-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fashon', '0006_ordercreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercreate',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
        migrations.CreateModel(
            name='PendingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashon.customer')),
            ],
        ),
    ]
